### PR TITLE
Update vscode config, add tslint and fix a bug

### PR DESCRIPTION
**Pull request by tamj0rd2**

### CODE REVIEW

**Comment by tamj0rd2** [comment]
Decided to make a new PR since the old one was getting too big and I didn't have much time to finish it.

**Comment by jvitor83** [comment]
@tamj0rd2 , is this PR done?
Can be merged?

**Comment by tamj0rd2** [comment]
Yep, it is @jvitor83

**Comment by jvitor83** [comment]
Great job @tamj0rd2 
Really appreciate!

**Pull request merged**
